#!/bin/bash

# new user sample name might be 'streams_getter' or 'scratch_10m' or 'scratch_nightly'

# default to test creds for scratcher. User must explicitly provide path to production creds
# or request production reds using --prod option.
# scratcher_creds_for_test
# scratcher_creds_for_prod

mydir=$(dirname "{BASH_SOURCE[0]}")

SHOWHELP=0
PRODACCT=test
POSITIONAL=()
end_of_options=0
while (( $# )); do
	if (( end_of_options )); then
		POSITIONAL+=("$1")
		shift
		continue
	fi
	
	case "$1" in
		--help | -h) 			SHOWHELP=1 ;;
		--prod)				    PRODACCT=prod ;;
		--)          			end_of_options=1 ;;
		-*)          			>&2 echo "error: unknown option: $1"; CLI_ERROR=1 ;;
		*)           			POSITIONAL+=("$1") ;;
	esac
	shift
done

set -- "${POSITIONAL[@]}"
##### END positional parameter handler #####

if (( SHOWHELP )); then
    echo "Creates user and initializes for test or production usage."
    echo
    echo "options:"
    echo "  --prod            creates user suitable for production environment"
	exit 0
fi

if (( $# == 0 )) || [[ -z "$1" ]]; then
    >&2 echo "error: valid user name parameter is required."
    exit 1
fi

(( CLI_ERROR )) && exit 1

set -ex

new_user=$1
new_user_home=/home/$new_user
authorized_keys=${PATH_TO_AUTHORIZED_KEYS:-~/.ssh/authorized_keys}
scratcher_creds=${PATH_TO_SCRATCHER_CREDS:-$mydir/scratcher_creds_for_$PRODACCT.ini}

# use --gecos to bypass the silly prompts for full name, room number, etc

cp_set_owner() {
	sudo cp $1 $2
	sudo chown $new_user:$new_user $2
}

sudo adduser $new_user --disabled-password --gecos "$new_user"
sudo mkdir -p                           $new_user_home/.ssh
sudo chmod 700                          $new_user_home/.ssh
sudo cp $authorized_keys                $new_user_home/.ssh/authorized_keys
sudo cp $mydir/id_github_readonly		$new_user_home/.ssh	
sudo cp $mydir/id_github_readonly.pub 	$new_user_home/.ssh
sudo chown -R $new_user:$new_user       $new_user_home/.ssh
sudo chmod 600                          $new_user_home/.ssh/authorized_keys

cp_set_owner $scratcher_creds           $new_user_home/scratcher_creds.ini

sudo mkdir -p /var/log/$new_user
sudo chown -R $new_user:$new_user /var/log/$new_user

echo "OPERATION COMPLETED SUCCESSFULLY"
